### ISSUE TITLE
Is it possible to edit large space 3DGS .ply?

### ISSUE THREAD

**Issue by a11enL** [playcanvas/supersplat#116]
I have a large space 3DGS .ply file, maybe 1 square kilometer, but even I zoom to max limit in Supersplat (0.19.2), the scene is still too small to see anything in the center. how can I modify the max zoom limit to edit something in the center? thanks.

**Comment by slimbuck** [comment]
Hi @a11enL,

Not sure if you're aware, but you can double-click the scene to set camera focal point. Then you can zoom and orbit around that point to inspect it.

If you are able to send me your scene I can test locally too.

Thanks!

**Comment by a11enL** [comment]
Thanks for your help, you can download the scene file from GDrive link:

https://drive.google.com/file/d/1vADXDNnbP5Zbwzf2jgjQKl4i9xA94Iq9/view?usp=sharing

Double-click is not working for me here.( supersplat 0.19.2)

**Comment by slimbuck** [comment]
Hi @a11enL,

The issue is there are two very very large splats in the scene, but they don't render. This explains why the scene appears so small on load - it's trying to fit in these two huge splats.

I will investigate why they don't render (presumably float32 rounding issues) and get back to you.

Thanks!

**Comment by slimbuck** [comment]
Hi @a11enL ,

I have recorded a video of me cleaning up this scene with the latest release of supersplat (v0.22.2).

It turns out there are some very very large splats (which don't even render) and also some completely transparent splats.

In the video below you can see me deleting the very large splats first (selecting them on the histogram) and then deleting the completely transparent ones.

https://github.com/user-attachments/assets/54e78e28-d91f-4704-9e44-b00ed1ea76f6

Thanks!
