### ISSUE TITLE
why sort by size or transparency removed from the selection panel?(v0.22.1)

### ISSUE THREAD

**Issue by TonyDua** [playcanvas/supersplat#130]
@slimbuck 
Hello, thank you for developing this project.  I have a question.  
Why was the option to sort by size or transparency removed from the selection panel in the latest version?  Was it because a bug was found?  Will these features be added back in a future version?  They were very useful and easy to use, so removing them has made some of my work impossible.  I look forward to your reply, thank you.

**Comment by slimbuck** [comment]
Hi @TonyDua ,

We removed the option of selecting by splat size or opacity, because these tools didn't work very well anyway. We added a new DATA panel (below the 3d viewport) which replaces this functionality.

If you open the DATA panel you can choose which splat property to view in the dropdown on the right (including splat size and opacity).

The histogram for the property you've chosen is plotted and you can now select splats directly on the histogram:

<img width="1464" alt="Screenshot 2024-07-12 at 10 50 50" src="https://github.com/user-attachments/assets/503f1d19-e377-44b4-b409-dcd8fd75f509">

Use shift to add to selection and ctrl to remove from selection, as usual.

We will release documentation and perhaps a video explaining the DATA panel when we release it. Hopefully users don't find it too confusing.

I'd appreciate any feedback on the new feature if you have a chance to give it a go.

Thanks!

**Comment by slimbuck** [comment]
Closing as answered. Please reopen if you have any more questions.
