### ISSUE TITLE
Question about loading 2DGS ply file, then saving 3DGS ply file's header

### ISSUE THREAD

**Issue by oUp2Uo** [playcanvas/supersplat#136]
Hi, thank you for adding 2DGS ply support.
But I found that the result ply header is not the same as original 3DGS ply.
![20240719125610](https://github.com/user-attachments/assets/330e7397-a673-4fbb-942b-5afac5b7aa37)
`property float scale_2` is added at the end, not after `property float scale_1`.
Maybe the order is not a error, but it would cause many programs reading error without check header.

**Comment by slimbuck** [comment]
Hi @oUp2Uo,

Yes you're right. At load time we add the `scale_2` data when loading 2dgs, but we don't remove it again when we write the file out.

I guess we should either flag the file as 2dgs on load and then remove `scale_2` when we save the file. Otherwise we could provide an option to the user.

Either way there is the question of what to do when a user loads a 2dgs and 3dgs file into the same scene. What do we save then?

**Comment by slimbuck** [comment]
(Oh and the order of the data in the file shouldn't matter, but I might move `scale_2` to appear after `scale_1` anyway, since it's definitely neater).

**Comment by oUp2Uo** [comment]
Thanks for the reply.
As you say, the order should not matter. But many programs do not check the header, and just reading data with the order: scale 0->1->2. In that case, error happens.
I think saving with `scale_2` is better. It could be used with normal 3dgs ply together.
If user want to process 2dgs model only, just need to manaully remove `scale_2` in the saved ply, which is not difficult.

**Comment by markinruc** [comment]
Hi！When I use the online SuperSlpat to process the output of 2dgs, the result I get cannot be rendered correctly in 2dgs, but it can be rendered in 3dgs. How can I handle the results obtained in order to continue using them in 2dgs. Thanks!
