### ISSUE TITLE
Some question about local development

### ISSUE THREAD

**Issue by Deaddawn** [playcanvas/supersplat#248]
Hi, there. I'm not sure if this is a problem, more like a question I want to ask. Well, I run supersplat using local development mode as instructed and use it in the localhost. I find that the supposed change won't happen on the website locally if I simply alter the code and rerun "npm run development" but will change if I clear the cache of the browser itself (chrome in my case, try others too) and then rerun it. Is this the normal way or I did something wrong?

**Comment by slimbuck** [comment]
Hi @Deaddawn,

The reason for this is that SuperSplat installs a service worker which caches the application files in browser in order to support offline / PWA mode.

When developing, I would suggest always running with Chrome DevTools open and in DevTools->Application->Service Workers, make sure "Update on reload" and "Bypass for network" are enabled:

<img width="1072" alt="Screenshot 2024-10-30 at 08 55 40" src="https://github.com/user-attachments/assets/de8de647-7627-437f-9167-45eab1a336ac">

Then you can reload as normal and your updates will take effect.

When testing in Safari you must select Develop->Empty Caches (option+cmd+e) always before reloading.

Hope that helps!

**Comment by Deaddawn** [comment]
> Hi @Deaddawn,
> 
> The reason for this is that SuperSplat installs a service worker which caches the application files in browser in order to support offline / PWA mode.
> 
> When developing, I would suggest always running with Chrome DevTools open and in DevTools->Application->Service Workers, make sure "Update on reload" and "Bypass for network" are enabled:
> 
> <img alt="Screenshot 2024-10-30 at 08 55 40" width="1072" src="https://private-user-images.githubusercontent.com/11276292/381466392-de8de647-7627-437f-9167-45eab1a336ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzkyMTEsIm5iZiI6MTczMDI3ODkxMSwicGF0aCI6Ii8xMTI3NjI5Mi8zODE0NjYzOTItZGU4ZGU2NDctNzYyNy00MzdmLTkxNjctNDVlYWIxYTMzNmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA5MDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMjA2ZTY1MDk0NGNjZDQ1NWM5ZjFlNDQ3MTlkMjUxNTJiZmQ5NTRmOTYzYWU0NjNmYTBhZWJlMWUwM2FmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.au3Ci7_vdztFUXTPijOQ-FA-6ZM3xRwy_NL8HrWeh9E">
> Then you can reload as normal and your updates will take effect.
> 
> When testing in Safari you must select Develop->Empty Caches (option+cmd+e) always before reloading.
> 
> Hope that helps!

Got it, thx
