### ISSUE TITLE
All adjustments to the Gaussian point color appearance should be converted into standard color representations, such as RGBA.

### ISSUE THREAD

**Issue by random-yang** [playcanvas/supersplat#305]
<img width="542" alt="image" src="https://github.com/user-attachments/assets/74284b09-a2f1-46f3-a73e-f63c7b457ea6">

If I'm not mistaken, based on the current implementation, the logic for adjusting color appearance has been extended to the splat shader logic.As a result, the color-adjusted ply files exported from this editor cannot be directly used in other Gaussian renderers.

<img width="682" alt="image" src="https://github.com/user-attachments/assets/e06e379c-0cb2-4a92-a548-46aabb352cc1">

**Comment by slimbuck** [comment]
Hi @random-yang,

You are correctly that we apply the coloring in the shader, but we do this in order to be memory efficient while supporting undo/redo.

The settings are applied the data upon save too, so you can export. See https://github.com/playcanvas/supersplat/blob/main/src/splat-serialize.ts#L129

Thanks!

**Comment by random-yang** [comment]
@slimbuck It sounds quite reasonable. Thanks!
