### ISSUE TITLE
how to rotate the camera pose or how to rotate the coordinate.

### ISSUE THREAD

**Issue by DavidCao1993** [playcanvas/supersplat#309]
thanks for your great jobs. i import cameras.json to add pose. the direction seems right but the rotation seems wrong:
![image](https://github.com/user-attachments/assets/5bc91410-3eb9-4467-8b08-a7222befff6b)
![cam1__10q00001](https://github.com/user-attachments/assets/9936cdb2-dc1a-4df9-b75f-399be999ab54)
how to solve this problem?

**Comment by DavidCao1993** [comment]
the first pic is the supersplat‘s pic. the second pic is the training pic.

**Comment by slimbuck** [comment]
Hi David, not sure. Could you provide the model and cameras.json?

**Comment by DavidCao1993** [comment]
[test_1.json](https://github.com/user-attachments/files/18020909/test_1.json)
[gs_test.ply.zip](https://github.com/user-attachments/files/18021105/gs_test.ply.zip)

**Comment by simonbethke** [comment]
In general, nerfstudio trains with Z-Up while Supersplat expects Y-Up. I already made nerfstudio store the up-axis into the ply-format so supersplat can compensate for this on load. But there was some resistance on the supersplat side. They also don't want to add the up-axis to the ply because there might by some jungle-software that isn't capable of reading those valid ply-files.
Compensating for the reorientation on load would have to be implemented in the engine-core and I don't make PRs there, so without pushing them, nothing will happen :(

**Comment by DavidCao1993** [comment]
i change the data's coordinate. thanks a lot.
