### ISSUE TITLE
[Bug] Splat clipping on HTML export

### ISSUE THREAD

**Issue by pablovela5620** [playcanvas/supersplat#318]
Exporting the following splat leads to some clipping problems. I've included the splat.ply file and a video to show how to reproduce

[used ply file](https://huggingface.co/datasets/pablovela5620/supersplat-example/resolve/main/splat-bedroom.ply)
[original discord messages](https://discord.com/channels/408617316415307776/1275850227663769686/1315016941169152071)

https://github.com/user-attachments/assets/4b47f9f1-383b-4fc5-a804-73a970c2cc50

**Comment by willeastcott** [comment]
It's these lines:

https://github.com/playcanvas/supersplat/blob/b15d8fc535503672a7fad4c0e4dde389f8918a66/src/templates/viewer-html-template.ts#L203-L204

You should be able to delete those from your exported HTML file and it should work much better.

I was _so close_ to querying this in your original PR @slimbuck. Any reason not to just go with the default values (near: 0.1, far: 1000)?

**Comment by slimbuck** [comment]
Actually for GS scenes we could probably just go with simple 0.01 to 10000 and disable front and back clipping entirely (like we do in SuperSplat). For GS scenes which tend to be around 1m == 1unit, this also makes sense.

In future though, soon as users want to combine GS with polygon models it becomes a different story since depth values much match.

**Comment by slimbuck** [comment]
This was fixed in the engine [here](https://github.com/playcanvas/engine/pull/7186).
