### ISSUE TITLE
Viewer app problem

### ISSUE THREAD

**Issue by hjodeiri** [playcanvas/supersplat#348]
Greetings,
Thank you for the new update. 
I exported the viewer app as a zip package, but it does not function properly when opened locally. After uncompressing the zip file, upon opening the HTML file on Chrome, it gets stuck at the loading screen and does not progress further (see the screenshot attached below). I tested it on an iPhone 15 Pro and experienced the same problem. Could you please assist in troubleshooting this issue?
Thank you for your support.

![image](https://github.com/user-attachments/assets/1285ad77-4686-477a-a818-d6756a077a2e)

**Comment by slimbuck** [comment]
Hi @hjodeiri ,

In order to run the zip version of the viewer, you must access the files through a server. You can't load the html file directly.

I do this using a python script on my Macbook:
```
#!/usr/bin/env python3
from http.server import HTTPServer, SimpleHTTPRequestHandler, test
import sys

class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer, port=int(sys.argv[1]) if len(sys.argv) > 1 else 8000)
```

I run this script from the folder containing the viewer files. Then I can access it from the browser using URL `http://localhost:8000/index.html` or similar.

The server script must have execution privileges on linux and mac, not sure how this works on windows.

Thanks!

**Comment by slimbuck** [comment]
Closing, but feel free to reopen if there's anything else we can help with!

**Comment by hjodeiri** [comment]
Thanks for your response. I was able to view the model in the web browser. However, the AR button does not appear on iOS.

**Comment by willeastcott** [comment]
Yeah, WebXR is an Android-only thing for the moment. Hopefully Apple will implement it on iOS some day in the future!
