### ISSUE TITLE
Cannot visualize my gaussian render

### ISSUE THREAD

**Issue by lazyDamon** [playcanvas/supersplat#360]
Hello! supersplat is very useful and I am so grateful for providing it.

My model can render, but the model cannot be visualized.
Has anyone encountered the same problem and have any suggestions?
![Screenshot from 2024-12-30 11-24-27](https://github.com/user-attachments/assets/f76e4077-58bf-42bf-95c0-4a9047934f45)

The ply file is attached.

[point_cloud.zip](https://github.com/user-attachments/files/18272781/point_cloud.zip)

**Comment by slimbuck** [comment]
Hi @lazyDamon,

Not sure what's going on with this model, will investigate.

Thanks for reporting this issue!

**Comment by slimbuck** [comment]
Ahh turns out this model contains NaNs at the beginning of X,Y,Z data and we don't handle this very well.

I'll work on a fix, but it's likely to take a little time since we must patch the engine.

Here it is loading up:
![Screenshot 2024-12-30 at 10 08 16](https://github.com/user-attachments/assets/4f2ec55a-a2eb-48dc-9abe-fb6426834661)
